---
- connection: local
  hosts: localhost
  roles:
    - vpc



#
#    Ansible (localhost) -> provision via AWS
#                        -> provision host A
#                        -> provision host B 

# Ansible/vagrant -> Jumpbox (proxy) -> configure host A
#                    -> configure host B

# Vagrant -> execute provision Ansible 
#         -> ok machines are on within vagrant, use jumpbox!! -> now provision!